name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven and generate a report
      run: mvn -B test --file pom.xml surefire-report:report

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: target/site/surefire-report.html

    - name: Generate coverage report
      run: mvn -B jacoco:report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Login to DockerHub
  #     uses: docker/login-action@v1
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}

  #   - name: Build and push Docker image
  #     uses: docker/build-push-action@v2
  #     with:
  #       context: .
  #       push: true
  #       tags: your-dockerhub-username/your-repo:latest